export const ERROR_CODES = {
  GENERATION_FORBIDDEN: { status: 403, message: '현재 계정은 이미지 생성 기능을 사용할 수 없습니다.' },
  GENERATION_DISABLED: { status: 503, message: '이미지 생성 API 활성화와 잔액 확인이 필요합니다.' },
  GENERATION_LIMIT: { status: 429, message: '생성 횟수 또는 테스트 예산 한도에 도달했습니다.' },
  GENERATION_FAILED: { status: 502, message: '이미지 생성에 실패했습니다. 이미 생성된 결과는 유지됩니다.' },
  INVALID_REQUEST: { status: 400, message: '요청 데이터가 올바르지 않습니다.' },
  INVALID_FILE_TYPE: { status: 400, message: '지원하지 않는 파일 형식입니다.' },
  FILE_TOO_LARGE: { status: 413, message: '파일 크기가 제한을 초과했습니다.' },
  IMAGE_DECODE_FAILED: { status: 422, message: '이미지를 읽을 수 없습니다.' },
  PROJECT_NOT_FOUND: { status: 404, message: '프로젝트를 찾을 수 없습니다.' },
  INVALID_PROJECT_TOKEN: { status: 401, message: '프로젝트 인증에 실패했습니다.' },
  INVALID_STATS_KEY: { status: 401, message: '통계 조회 인증에 실패했습니다.' },
  EMAIL_ALREADY_REGISTERED: { status: 409, message: '이미 가입된 이메일입니다.' },
  INVALID_CREDENTIALS: { status: 401, message: '이메일 또는 비밀번호가 올바르지 않습니다.' },
  CURRENT_PASSWORD_INCORRECT: { status: 400, message: '현재 비밀번호가 올바르지 않습니다.' },
  PASSWORD_CHANGE_UNAVAILABLE: { status: 400, message: '이메일로 가입한 계정만 비밀번호를 변경할 수 있습니다.' },
  UNAUTHORIZED: { status: 401, message: '로그인이 필요합니다.' },
  NAVER_NOT_CONFIGURED: { status: 503, message: '네이버 로그인이 설정되어 있지 않습니다.' },
  NAVER_LOGIN_FAILED: { status: 502, message: '네이버 로그인에 실패했습니다.' },
  GOOGLE_LOGIN_FAILED: { status: 401, message: 'Google 로그인 인증에 실패했습니다.' },
  GOOGLE_ACCOUNT_CONFLICT: { status: 409, message: '이미 다른 Google 계정과 연결된 이메일입니다.' },
  FEEDBACK_NOT_CONFIGURED: { status: 503, message: '피드백 기능이 아직 설정되어 있지 않습니다.' },
  FEEDBACK_SUBMIT_FAILED: { status: 502, message: '피드백 전송에 실패했습니다.' },
  OGQ_NOT_CONFIGURED: { status: 503, message: 'OGQ 마켓 연동이 아직 설정되어 있지 않습니다.' },
  OGQ_REQUEST_FAILED: { status: 502, message: 'OGQ 마켓 조회에 실패했습니다.' },
  UPLOAD_NOT_COMPLETED: { status: 409, message: '업로드가 완료되지 않았습니다.' },
  PROCESS_ALREADY_RUNNING: { status: 409, message: '이미 처리 중인 프로젝트입니다.' },
  OCR_TEXT_NOT_FOUND: { status: 422, message: '이미지에서 텍스트를 찾지 못했습니다.' },
  OCR_KOREAN_NOT_FOUND: { status: 422, message: '이미지에서 한국어 텍스트를 찾지 못했습니다. 선명한 PNG 파일로 다시 시도해주세요.' },
  OCR_PROVIDER_UNAVAILABLE: { status: 503, message: 'OCR 엔진을 시작하지 못했습니다. 잠시 후 다시 시도해주세요.' },
  OCR_PROVIDER_FAILED: { status: 502, message: 'OCR 처리 중 오류가 발생했습니다.' },
  TRANSLATION_PROVIDER_UNAVAILABLE: { status: 503, message: '번역 엔진이 설정되어 있지 않습니다.' },
  TRANSLATION_PROVIDER_FAILED: { status: 502, message: '번역 처리 중 오류가 발생했습니다.' },
  IMAGE_CLEANUP_FAILED: { status: 500, message: '이미지 정리 중 오류가 발생했습니다.' },
  RATE_LIMITED: { status: 429, message: '요청이 너무 많습니다. 잠시 후 다시 시도해주세요.' },
  NOT_FOUND: { status: 404, message: '요청한 리소스를 찾을 수 없습니다.' },
  INTERNAL_ERROR: { status: 500, message: '내부 서버 오류가 발생했습니다.' },
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
