import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Navigate, useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Download, Globe2, ImagePlus, LoaderCircle, ShieldCheck, Sparkles } from 'lucide-react'
import Header from '../components/Header'
import NavMenu from '../components/NavMenu'
import Button from '../components/Button'
import Modal from '../components/Modal'
import { useAuth } from '../store/AuthContext'
import { useSiteLang } from '../i18n/LanguageContext'
import { generationCopy } from '../i18n/generation'
import { downloadGeneration, downloadGenerationSet, fetchGenerationFile, generationRequest, latestCompletedImages, prepareReference, type GenerationImage, type GenerationProject, type StickerPlanItem } from '../lib/generationApi'
import { useUploads } from '../store/uploads'

const categories = ['animal', 'person', 'food', 'object', 'fantasy'] as const
const tags = ['cute', 'simple', 'pastel', 'bold', 'playful', 'chic', 'warm', 'funny'] as const
const conditions = { animal: 'animal character', person: 'human character', food: 'food character', object: 'object character', fantasy: 'fantasy character', cute: 'cute', simple: 'simple design', pastel: 'pastel colors', bold: 'bold outlines', playful: 'playful personality', chic: 'chic personality', warm: 'warm and friendly', funny: 'humorous and expressive' }

function GenerationPageSkeleton({ label }: { label: string }) {
  return <div role="status" aria-label={label} aria-busy="true" className="mt-8 grid animate-pulse gap-5 motion-reduce:animate-none lg:grid-cols-[1fr_340px]"><span className="sr-only">{label}</span><div className="rounded-[28px] border border-gray-200 bg-white p-6"><div className="h-6 w-40 rounded bg-gray-200" /><div className="mx-auto mt-6 aspect-[740/640] max-w-md rounded-2xl bg-gray-100" /><div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-6">{Array.from({ length: 24 }, (_, i) => <div key={i} className="aspect-square rounded-xl bg-gray-100" />)}</div></div><div className="h-80 rounded-[28px] border border-gray-200 bg-white" /></div>
}

export default function Generate() {
  const { token } = useAuth(); const navigate = useNavigate(); const { addFiles } = useUploads(); const { lang } = useSiteLang(); const t = generationCopy(lang)
  const [params, setParams] = useSearchParams(); const [projects, setProjects] = useState<GenerationProject[]>([]); const [enabled, setEnabled] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  const [prompt, setPrompt] = useState(''); const [reference, setReference] = useState<string>(); const [category, setCategory] = useState<typeof categories[number]>(); const [selectedTags, setSelectedTags] = useState<typeof tags[number][]>([]); const [dragging, setDragging] = useState(false); const [uploading, setUploading] = useState(false)
  const [slot, setSlot] = useState(0); const [caption, setCaption] = useState(''); const [revision, setRevision] = useState(''); const [planDraft, setPlanDraft] = useState<StickerPlanItem[]>([]); const [completeOpen, setCompleteOpen] = useState(false)
  const fileInput = useRef<HTMLInputElement>(null); const polling = useRef(false)
  const activeProject = projects.find(item => (item.status ?? 'active') === 'active')
  const project = projects.find(item => item.id === params.get('project')) ?? (params.get('new') === '1' ? undefined : activeProject ?? projects[0])
  polling.current = projects.some(item => item.images.some(image => ['queued', 'running'].includes(image.status)))
  const completedImages = useMemo(() => project ? latestCompletedImages(project) : [], [project])
  const completedSlots = useMemo(() => new Set(completedImages.map(image => image.slot)), [completedImages])
  const latest = project?.images.filter(image => image.slot === slot).at(-1)
  const image = completedImages.find(item => item.slot === slot)
  const projectStatus = project?.status ?? (completedImages.length === 24 ? 'completed' : 'active')
  const busy = submitting || !!project?.images.some(item => ['queued', 'running'].includes(item.status))
  const plan = useMemo(() => project?.plan ?? [], [project])
  const load = useCallback(async () => { if (!token) return; const [config, result] = await Promise.all([generationRequest<{ enabled: boolean }>(token, '/config'), generationRequest<{ projects: GenerationProject[] }>(token, '/projects')]); setEnabled(config.enabled); setProjects(result.projects) }, [token])
  useEffect(() => { let disposed = false; const refresh = async () => { try { await load() } catch (reason) { if (!disposed) setError(reason instanceof Error ? reason.message : 'API error') } finally { if (!disposed) setLoading(false) } }; void refresh(); const interval = setInterval(() => { if (polling.current && document.visibilityState === 'visible') void refresh() }, 4000); return () => { disposed = true; clearInterval(interval) } }, [load])
  useEffect(() => { setCaption(image?.caption ?? ''); setRevision(latest?.prompt ?? '') }, [image?.id, image?.caption, latest?.id, latest?.prompt])
  useEffect(() => { setPlanDraft(plan) }, [plan])
  const action = async (fn: () => Promise<void>) => { setSubmitting(true); setError(''); try { await fn(); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'API error') } finally { setSubmitting(false) } }
  const create = () => action(async () => { const instructions = [category ? `Category: ${conditions[category]}.` : '', selectedTags.length ? `Style and personality: ${selectedTags.map(tag => conditions[tag]).join(', ')}.` : '', prompt.trim()].filter(Boolean).join('\n'); const created = await generationRequest<GenerationProject>(token!, '/projects', 'POST', { prompt: instructions, reference }); setProjects(previous => [created, ...previous]); setParams({ project: created.id }); await generationRequest(token!, `/projects/${created.id}/images`, 'POST', { slot: 0, prompt: '중립 표정으로 전체 캐릭터 디자인을 보여주세요.' }) })
  const attach = async (files: FileList | null) => { if (!files?.length || uploading) return; if (files.length !== 1) { setError(t.oneImage); return } setUploading(true); setError(''); try { setReference(await prepareReference(files[0])) } catch { setError(t.imageError) } finally { setUploading(false) } }
  const createPlan = () => action(async () => { const result = await generationRequest<{ plan: StickerPlanItem[] }>(token!, `/projects/${project!.id}/plan`, 'POST'); setPlanDraft(result.plan) })
  const savePlan = async () => { await generationRequest(token!, `/projects/${project!.id}/plan`, 'PATCH', { plan: planDraft }) }
  const generateNext = () => action(async () => { await savePlan(); const slots = planDraft.filter(item => !completedSlots.has(item.slot)).slice(0, 4).map(item => item.slot); if (!slots.length) return; await generationRequest(token!, `/projects/${project!.id}/batch`, 'POST', { slots }); setSlot(slots[0]) })
  const sendToLocalization = async () => { if (!project || projectStatus !== 'completed') return; setSubmitting(true); setError(''); try { const files: File[] = []; for (let start = 0; start < completedImages.length; start += 4) files.push(...await Promise.all(completedImages.slice(start, start + 4).map(item => fetchGenerationFile(token!, project.id, item.id, item.slot)))); addFiles(files); navigate('/localize') } catch (reason) { setError(reason instanceof Error ? reason.message : 'API error') } finally { setSubmitting(false) } }
  const startNew = () => { if (activeProject) { setParams({ project: activeProject.id }); setError(t.activeExists); return } setParams({ new: '1' }); setSlot(0); setPrompt(''); setReference(undefined); setCategory(undefined); setSelectedTags([]); setError('') }
  if (!token) return <Navigate to="/login?next=/generate" replace />
  const cost = project?.images.reduce((sum, item) => sum + Number(item.cost_usd ?? item.reserve_usd), 0) ?? 0
  const cardImage = (item: GenerationImage | undefined, label: string) => item?.url ? <img src={item.url} alt={label} className="h-full w-full object-contain" /> : <Sparkles className="h-8 w-8 text-brand/35" />

  return <div className="min-h-screen bg-[#FAFBFC]"><Header center={<NavMenu workspace />} sticky /><main className="layout-app py-8 sm:py-12">
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm font-bold text-brand-dark">Glocalizer · {t.sample}</p><Button variant="outline" onClick={startNew} disabled={busy || uploading}>{t.new}</Button></div><h1 className="mt-4 text-[28px] font-extrabold tracking-tight sm:text-[36px]">{t.title}</h1><p className="mt-3 text-sub">{t.subtitle}</p>
    {!enabled && !loading && <p role="status" className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{t.disabled}</p>}{error && <div role="alert" className="mt-5 flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-red-50 p-4 text-sm text-red-700"><span>{error}</span><Button variant="ghost" size="sm" onClick={() => action(load)}>{t.retry}</Button></div>}
    {loading ? <GenerationPageSkeleton label={t.loading} /> : !project ? <section className="mx-auto mt-10 max-w-2xl rounded-[28px] border border-gray-200 bg-white p-5 sm:p-7">
      <div onDragOver={event => { event.preventDefault(); setDragging(true) }} onDragLeave={event => { if (!event.currentTarget.contains(event.relatedTarget as Node | null)) setDragging(false) }} onDrop={event => { event.preventDefault(); setDragging(false); void attach(event.dataTransfer.files) }} className={`flex min-h-60 flex-col items-center justify-center gap-3 rounded-3xl border-2 border-dashed p-6 text-center ${dragging ? 'border-brand bg-brand-soft' : 'border-gray-200 bg-[#FAFBFC]'}`}>{reference ? <><img src={reference} alt={t.attach} className="h-32 w-full object-contain" /><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => fileInput.current?.click()}>{t.fileSelect}</Button><Button variant="ghost" size="sm" onClick={() => setReference(undefined)}>{t.remove}</Button></div></> : <><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-brand-soft text-brand-dark">{uploading ? <LoaderCircle className="animate-spin" size={30} /> : <ImagePlus size={30} />}</span><h2 className="font-extrabold">{t.dropTitle}</h2><p className="text-sm text-sub">{t.dropHelp}</p><Button size="sm" onClick={() => fileInput.current?.click()}>{t.fileSelect}</Button></>}</div><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={event => { void attach(event.target.files); event.target.value = '' }} />
      <fieldset className="mt-6"><legend className="text-sm font-bold">{t.category}<span className="ml-2 text-xs font-normal text-sub">{t.optional}</span></legend><div className="mt-3 flex flex-wrap gap-2">{categories.map(value => <button key={value} type="button" aria-pressed={category === value} onClick={() => setCategory(previous => previous === value ? undefined : value)} className={`rounded-full border px-4 py-2 text-sm font-bold ${category === value ? 'border-brand bg-brand-soft text-brand-dark' : 'border-gray-200 text-sub'}`}>{t[value]}</button>)}</div></fieldset>
      <fieldset className="mb-6 mt-5"><legend className="text-sm font-bold">{t.tags}<span className="ml-2 text-xs font-normal text-sub">{t.optional}</span></legend><div className="mt-3 flex flex-wrap gap-2">{tags.map(value => <button key={value} type="button" aria-pressed={selectedTags.includes(value)} onClick={() => setSelectedTags(previous => previous.includes(value) ? previous.filter(tag => tag !== value) : [...previous, value])} className={`rounded-full border px-3 py-1.5 text-sm ${selectedTags.includes(value) ? 'border-brand bg-brand-soft font-bold text-brand-dark' : 'border-gray-200 text-sub'}`}># {t[value]}</button>)}</div></fieldset>
      <label htmlFor="character-prompt" className="font-bold">{t.prompt}</label><textarea id="character-prompt" value={prompt} onChange={event => setPrompt(event.target.value)} maxLength={700} placeholder={t.placeholder} className="mt-4 min-h-32 w-full resize-y rounded-2xl bg-surface p-4 outline-none focus:ring-2 focus:ring-brand" /><div className="mt-4 flex justify-end"><Button onClick={create} disabled={!enabled || submitting || uploading || !prompt.trim()}><Sparkles size={18} />{t.create}</Button></div>
    </section> : <><section className="mt-8 rounded-3xl border border-gray-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-brand-dark">{projectStatus === 'completed' ? t.statusCompleted : t.statusActive}</p><h2 className="mt-1 text-xl font-extrabold">{completedImages.length}/24 {t.progress}</h2></div>{projectStatus === 'completed' && <CheckCircle2 className="text-brand" />}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-brand transition-[width]" style={{ width: `${completedImages.length / 24 * 100}%` }} /></div></section>
      <div className="mt-5 grid items-start gap-5 lg:grid-cols-[1fr_340px]"><section className="min-w-0 rounded-[28px] border border-gray-200 bg-white p-5 sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-extrabold">{slot === 0 ? t.base : `${t.expressions} ${slot}`}</h2>{project.confirmed && <span className="rounded-full bg-brand-soft px-3 py-1 text-xs font-bold text-brand-dark">{t.confirmed}</span>}</div><p className="mt-2 break-words text-sm text-sub">{project.prompt}</p>
        <div className="relative mx-auto mt-5 flex aspect-[740/640] max-w-md items-center justify-center overflow-hidden rounded-2xl border border-gray-100 bg-[repeating-conic-gradient(#f2f4f6_0%_25%,white_0%_50%)] bg-[length:20px_20px]">{cardImage(image, slot === 0 ? t.base : `${t.expressions} ${slot}`)}{caption && image && <span className="absolute left-0 right-0 top-[2%] text-center text-[clamp(15px,3vw,22px)] font-black text-ink [paint-order:stroke] [-webkit-text-stroke:3px_white]">{caption}</span>}{latest && (latest.status === 'queued' || latest.status === 'running') && <span role="status" className="absolute bottom-4 flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm shadow-sm"><LoaderCircle size={16} className="animate-spin" />{latest.status === 'queued' ? t.queued : t.running}</span>}</div>{latest?.error && <p className="mt-3 text-sm text-red-600">{latest.error}</p>}{!latest && <p className="mt-3 text-sm text-sub">{t.missing}</p>}
        <div className="mt-5 grid grid-cols-4 gap-2 sm:grid-cols-6">{Array.from({ length: 24 }, (_, currentSlot) => { const completed = completedImages.find(item => item.slot === currentSlot); const newest = project.images.filter(item => item.slot === currentSlot).at(-1); return <button key={currentSlot} type="button" onClick={() => setSlot(currentSlot)} aria-pressed={slot === currentSlot} className={`overflow-hidden rounded-xl border-2 p-1 ${slot === currentSlot ? 'border-brand bg-brand-soft' : 'border-gray-100'}`}><div className="flex aspect-square items-center justify-center">{cardImage(completed, `${currentSlot + 1}`)}</div><span className="block truncate text-[11px]">{newest && newest.status !== 'completed' ? t[newest.status] : currentSlot === 0 ? t.base : `${currentSlot + 1}`}</span></button> })}</div>
        {slot === 0 && !project.confirmed && <Button className="mt-5 w-full" disabled={!image || busy} onClick={() => action(async () => { await generationRequest(token, `/projects/${project.id}/confirm`, 'POST'); setSlot(1) })}>{t.confirm}<ArrowRight size={16} /></Button>}{!latest && slot === 0 && <Button className="mt-3 w-full" onClick={() => action(async () => { await generationRequest(token, `/projects/${project.id}/images`, 'POST', { slot: 0, prompt: '중립 표정으로 전체 캐릭터 디자인을 보여주세요.' }) })} disabled={busy || !enabled}>{t.create}</Button>}<p className="mt-5 text-xs leading-5 text-sub">{t.format}</p></section>
      <aside className="min-w-0 space-y-5">{project.confirmed && projectStatus === 'active' && <section className="rounded-3xl border border-gray-200 bg-white p-5"><h2 className="font-extrabold">{t.planTitle}</h2><p className="mt-2 text-sm leading-6 text-sub">{t.planDescription}</p>{planDraft.length === 0 ? <Button className="mt-4 w-full" disabled={busy} onClick={createPlan}><Sparkles size={17} />{t.createPlan}</Button> : <><details className="mt-4"><summary className="cursor-pointer rounded-xl bg-surface px-4 py-3 text-sm font-bold">{t.editPlan}</summary><div className="mt-3 max-h-[480px] space-y-3 overflow-y-auto pr-1">{planDraft.map((item, index) => <div key={item.slot} className="rounded-2xl border border-gray-100 p-3"><p className="text-xs font-extrabold text-brand-dark">{item.slot + 1}/24</p><input value={item.pose} disabled={completedSlots.has(item.slot)} maxLength={500} onChange={event => setPlanDraft(previous => previous.map((value, current) => current === index ? { ...value, pose: event.target.value } : value))} className="mt-2 w-full rounded-xl border border-gray-200 p-2.5 text-sm disabled:bg-gray-50" /><input value={item.caption} disabled={completedSlots.has(item.slot)} maxLength={16} onChange={event => setPlanDraft(previous => previous.map((value, current) => current === index ? { ...value, caption: event.target.value } : value))} className="mt-2 w-full rounded-xl border border-gray-200 p-2.5 text-sm disabled:bg-gray-50" /></div>)}</div><Button variant="outline" className="mt-3 w-full" disabled={busy || planDraft.some(item => !item.pose.trim())} onClick={() => action(savePlan)}>{t.savePlan}</Button></details><Button className="mt-4 w-full" disabled={!enabled || busy || completedImages.length === 24 || planDraft.some(item => !item.pose.trim())} onClick={generateNext}>{t.nextBatch}</Button></>}</section>}
        {image && <section className="rounded-3xl border border-gray-200 bg-white p-5"><label className="text-sm font-bold" htmlFor="sticker-caption">{t.caption}</label><input id="sticker-caption" maxLength={16} value={caption} disabled={projectStatus === 'completed'} onChange={event => setCaption(event.target.value)} className="mt-3 w-full rounded-xl border border-gray-200 p-3 disabled:bg-gray-50" />{projectStatus === 'active' && <Button variant="outline" className="mt-3 w-full" disabled={submitting} onClick={() => action(async () => { await generationRequest(token, `/projects/${project.id}/images/${image.id}`, 'PATCH', { caption }) })}>{t.save}</Button>}<Button className="mt-2 w-full" disabled={submitting} onClick={() => action(async () => { if (projectStatus === 'active') await generationRequest(token, `/projects/${project.id}/images/${image.id}`, 'PATCH', { caption }); await downloadGeneration(token, project.id, image.id) })}>{t.download}</Button></section>}
        {latest && projectStatus === 'active' && !(slot === 0 && project.confirmed) && <section className="rounded-3xl border border-gray-200 bg-white p-5"><label htmlFor="revision" className="text-sm font-bold">{t.editPrompt}</label><textarea id="revision" value={revision} maxLength={500} onChange={event => setRevision(event.target.value)} className="mt-3 min-h-20 w-full rounded-xl border border-gray-200 p-3" /><Button variant="outline" className="mt-3 w-full" disabled={!enabled || busy || !revision.trim()} onClick={() => action(async () => { await generationRequest(token, `/projects/${project.id}/images`, 'POST', { slot, prompt: revision }) })}>{t.regenerate}</Button></section>}
        {projectStatus === 'active' && completedImages.length === 24 && <section className="rounded-3xl border border-brand/20 bg-brand-soft/50 p-5"><h2 className="font-extrabold">{t.readyTitle}</h2><p className="mt-2 text-sm leading-6 text-sub">{t.readyDescription}</p><Button className="mt-4 w-full" onClick={() => setCompleteOpen(true)} disabled={busy}>{t.complete}</Button></section>}
        {projectStatus === 'completed' && <section className="rounded-3xl border border-brand/20 bg-brand-soft/50 p-5"><h2 className="font-extrabold">{t.nextTitle}</h2><p className="mt-2 text-sm leading-6 text-sub">{t.nextDescription}</p><Button className="mt-4 w-full" disabled={submitting} onClick={() => action(async () => { await downloadGenerationSet(token, project) })}><Download size={17} />{t.downloadSet}</Button><Button variant="outline" className="mt-2 w-full" disabled={submitting} onClick={() => { void sendToLocalization() }}><Globe2 size={17} />{t.localizeNext}</Button><Button variant="outline" className="mt-2 w-full" onClick={() => navigate('/review')}><ShieldCheck size={17} />{t.reviewNext}</Button></section>}<p className="px-2 text-xs leading-5 text-sub">{t.budget}: ${cost.toFixed(3)}<br />{t.unknown}<br />{t.limit}</p></aside></div></>}
    <section className="mt-10"><h2 className="text-lg font-extrabold">{t.history}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{projects.map(item => { const thumbnail = latestCompletedImages(item)[0]; const count = latestCompletedImages(item).length; return <button key={item.id} onClick={() => { setParams({ project: item.id }); setSlot(0) }} className="flex min-w-0 items-center gap-3 rounded-2xl border border-gray-200 bg-white p-4 text-left"><span className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-brand-soft">{thumbnail?.url ? <img src={thumbnail.url} alt="" className="h-full w-full object-contain" /> : <Sparkles size={20} />}</span><span className="min-w-0"><span className="block truncate font-bold">{item.prompt}</span><span className="text-xs text-sub">{item.day} · {count}/24 · {(item.status ?? (count === 24 ? 'completed' : 'active')) === 'completed' ? t.statusCompleted : t.statusActive}</span></span></button> })}</div></section>
  </main>{completeOpen && project && <Modal onClose={() => { if (!submitting) setCompleteOpen(false) }} labelledBy="complete-project-title" closeLabel={t.cancel}><h2 id="complete-project-title" className="pr-8 text-xl font-extrabold">{t.completeTitle}</h2><p className="mt-3 text-sm leading-6 text-sub">{t.completeDescription}</p><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setCompleteOpen(false)} disabled={submitting}>{t.cancel}</Button><Button onClick={() => action(async () => { await generationRequest(token, `/projects/${project.id}/complete`, 'POST'); setCompleteOpen(false) })} disabled={submitting}>{t.complete}</Button></div></Modal>}</div>
}
