import type { SiteLang } from './translations'
const copy = {
  dropTitle: ['참고 이미지를 여기에 끌어다 놓으세요', 'Drop a reference image here', '参考画像をここにドラッグしてください', '将参考图片拖到这里'],
  dropHelp: ['PNG · JPG · WebP · 참고 이미지 1장 (최대 10MB)', 'PNG · JPG · WebP · One reference image (up to 10MB)', 'PNG・JPG・WebP・参考画像1枚（最大10MB）', 'PNG · JPG · WebP · 1张参考图片（最大10MB）'],
  fileSelect: ['파일 선택', 'Choose file', 'ファイルを選択', '选择文件'],
  optional: ['선택 사항', 'Optional', '任意', '可选'],
  category: ['캐릭터 카테고리', 'Character category', 'キャラクターのカテゴリー', '角色类别'],
  tags: ['스타일·성격 태그', 'Style and personality tags', '画風・性格タグ', '风格与性格标签'],
  animal: ['동물', 'Animal', '動物', '动物'], person: ['사람', 'Person', '人物', '人物'], food: ['음식', 'Food', '食べ物', '食物'], object: ['사물', 'Object', '物', '物品'], fantasy: ['상상 캐릭터', 'Fantasy character', '空想キャラクター', '幻想角色'],
  cute: ['귀여운', 'Cute', 'かわいい', '可爱'], simple: ['심플한', 'Simple', 'シンプル', '简约'], pastel: ['파스텔', 'Pastel', 'パステル', '柔和配色'], bold: ['굵은 선', 'Bold outlines', '太い線', '粗线条'], playful: ['장난꾸러기', 'Playful', 'いたずら好き', '调皮'], chic: ['시크한', 'Chic', 'クール', '高冷'], warm: ['따뜻한', 'Warm', '温かい', '温暖'], funny: ['익살스러운', 'Funny', 'ユーモラス', '搞怪'],
  oneImage: ['참고 이미지는 1장만 선택해주세요.', 'Please choose one reference image.', '参考画像は1枚だけ選択してください。', '请选择1张参考图片。'],
  imageError: ['PNG·JPG·WebP 이미지 1장(최대 10MB)을 사용해주세요. 복잡한 이미지는 크기를 줄여주세요.', 'Use one PNG, JPG or WebP image up to 10MB. Reduce the size of complex images.', '最大10MBのPNG・JPG・WebPを1枚使用してください。複雑な画像は小さくしてください。', '请使用1张不超过10MB的PNG、JPG或WebP，复杂图片请缩小尺寸。'],
  title: ['어떤 이모티콘을 만들까요?', 'What sticker would you like to create?', 'どんなスタンプを作りますか？', '想生成什么表情贴纸？'],
  subtitle: ['아이디어를 캐릭터로, 캐릭터를 다양한 표정으로.', 'Turn an idea into a character, then explore expressions.', 'アイデアをキャラクターに、様々な表情に。', '将创意变成角色，再赋予不同表情。'],
  sample: ['대표 캐릭터 + 표정 3장 · 샘플', 'One character + three expressions · Sample', 'キャラクター1枚＋表情3枚・サンプル', '角色1张＋表情3张 · 示例'],
  prompt: ['캐릭터와 그림체를 설명해주세요', 'Describe your character and style', 'キャラクターと画風を説明してください', '请描述角色与画风'],
  placeholder: ['동그란 크림색 고양이. 굵은 선과 파스텔 색상의 귀여운 캐릭터.', 'A round cream-colored cat, bold outlines and pastel colors.', '丸いクリーム色の猫。太い線とパステルカラー。', '圆圆的奶油色猫，粗线条和柔和配色。'],
  attach: ['참고 이미지 첨부', 'Attach reference', '参考画像を添付', '添加参考图片'], remove: ['첨부 삭제', 'Remove reference', '添付を削除', '移除参考图片'],
  create: ['대표 캐릭터 만들기', 'Create character', 'キャラクターを生成', '生成角色'], confirm: ['이 캐릭터로 진행', 'Use this character', 'このキャラクターで進む', '使用此角色'], confirmed: ['캐릭터 확정됨', 'Character confirmed', 'キャラクター確定済み', '角色已确认'], base: ['대표 캐릭터', 'Base character', '基本キャラクター', '基础角色'], expressions: ['표정과 포즈', 'Expressions and poses', '表情とポーズ', '表情与姿势'], generate: ['표정 3장 만들기', 'Generate 3 expressions', '表情3枚を生成', '生成3张表情'], regenerate: ['선택 재생성', 'Regenerate selected', '選択画像を再生成', '重新生成所选图片'], caption: ['한국어 문구 (최대 16자)', 'Korean caption (up to 16 characters)', '韓国語の文言（最大16文字）', '韩语文案（最多16字）'], save: ['문구 저장', 'Save caption', '文言を保存', '保存文案'], download: ['PNG 다운로드', 'Download PNG', 'PNGをダウンロード', '下载PNG'], saved: ['저장했어요', 'Saved', '保存しました', '已保存'], queued: ['대기 중', 'Queued', '待機中', '等待中'], running: ['생성 중', 'Generating', '生成中', '生成中'], failed: ['생성 실패', 'Generation failed', '生成失敗', '生成失败'], missing: ['아직 생성하지 않았어요', 'Not generated yet', 'まだ生成されていません', '尚未生成'],
  disabled: ['API 활성화와 잔액 확인 후 생성할 수 있어요.', 'Enable the API and check the balance to generate.', 'APIの有効化と残高確認後に生成できます。', '启用API并确认余额后即可生成。'],
  limit: ['하루 1세트 · 추가 시도 최대 2회. 실패한 시도도 포함돼요.', 'One set per day · Two extra attempts, including failures.', '1日1セット・追加試行2回。失敗も含みます。', '每天1组，额外尝试2次，失败也计入。'], budget: ['사용량 기반 예상 비용', 'Estimated cost from usage', '使用量に基づく推定費用', '根据使用量估算的费用'], unknown: ['사용량 미확인 호출은 예약 예산으로 계산해요.', 'Unknown usage retains its budget reservation.', '不明な使用量は予約予算で計算します。', '未报告使用量的调用按预留预算计算。'], format: ['740 × 640 · 투명 PNG · OGQ 제출용 24장 세트가 아닌 샘플이에요.', '740 × 640 · Transparent PNG · Sample, not a complete OGQ set.', '740 × 640・透過PNG・OGQ提出用の完成セットではありません。', '740 × 640 · 透明PNG · 示例，并非OGQ完整套装。'], new: ['새 작업', 'New project', '新しい作業', '新建任务'], history: ['생성 작업', 'Generation projects', '生成した作業', '生成任务'], loading: ['작업을 불러오는 중…', 'Loading projects…', '読み込み中…', '正在加载…'], retry: ['다시 불러오기', 'Reload', '再読み込み', '重新加载'], editPrompt: ['표정·포즈 또는 수정 요청', 'Expression, pose or revision', '表情・ポーズ・修正内容', '表情、姿势或修改要求'], happy: ['웃으며 인사하는 모습', 'Smiling and waving hello', '笑顔で挨拶する', '笑着打招呼'], sad: ['눈물을 흘리며 슬퍼하는 모습', 'Crying with a sad expression', '涙を流して悲しむ', '流泪难过'], love: ['하트를 안고 사랑을 표현하는 모습', 'Hugging a heart', 'ハートを抱く', '抱着爱心'], empty: ['저장된 생성 작업이 없어요', 'No saved generation projects', '保存された生成作業はありません', '没有保存的生成任务'],
} satisfies Record<string, [string, string, string, string]>
export function generationCopy(lang: SiteLang) { const index = ({ ko: 0, en: 1, ja: 2, zh: 3 })[lang]; return Object.fromEntries(Object.entries(copy).map(([key, values]) => [key, values[index]])) as Record<keyof typeof copy, string> }
